services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - gitboss-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  gitboss-network:
    driver: bridge
